name: InstaWall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  cached_network_image:
  flutter_staggered_grid_view:
  external_path:
  media_scanner:
  responsive_sizer: ^3.3.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

